services:
    sg_datatables.serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    sg_datatables.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
    sg_datatables.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - ['@sg_datatables.serializer.method']
            - ['@sg_datatables.serializer.encoder.json']
    sg_datatables.twig.extension:
        class: Sg\DatatablesBundle\Twig\DatatableTwigExtension
        arguments: ['@translator']
        tags:
            - { name: twig.extension }
    sg_datatables.datatable.abstract:
        class: Sg\DatatablesBundle\Datatable\View\AbstractDatatableView
        abstract: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@twig'
            - '@translator.default'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - 
                base: 'SgDatatablesBundle:Datatable:datatable.html.twig'
                html: 'SgDatatablesBundle:Datatable:datatable_html.html.twig'
                js: 'SgDatatablesBundle:Datatable:datatable_js.html.twig'
    sg_datatables.query:
        class: Sg\DatatablesBundle\Datatable\Data\DatatableDataManager
        arguments:
            - '@request_stack'
            - '@sg_datatables.serializer'
            - '%sg_datatables.datatable.query%'
            - '%kernel.bundles%'

#    sg_datatables.query:
#        class: Sg\DatatablesBundle\Datatable\Data\DatatableDataManager
#        arguments: ['@request_stack', '@sg_datatables.serializer', %sg_datatables.datatable.query%, %kernel.bundles%]
